### PR TITLE
update terraform to v0.12.6

### LINKED ISSUE #233: Update terraform to v0.12.6
Per Hashicorp:

> Hi folks :wave: If you’ve upgraded to Terraform 0.12 support, please note that there have been various Provider SDK fixes that have been released in the last few dot releases of Terraform. The latest dependency available is github.com/hashicorp/terraform@v0.12.6 and we would recommend updating to that version when possible.

### PR DESCRIPTION
**Pull request by davidji99**
Fixes #233

### CODE REVIEW

**Comment by mars** [comment]
Hashicorp CI passed ✅

@davidji99 did you check that this branch works when used with `terraform` CLI? If so, then this is good to go.

**Comment by davidji99** [comment]
> @davidji99 did you check that this branch works when used with `terraform` CLI? If so, then this is good to go.

Hey @mars,

Yeah I did with `terraform` version v0.12.6. But I can spot a previous 0.12.X version just in case.

**Comment by davidji99** [comment]
Tested this branch against a sample repository using `terraform v0.12.3`. Is this the scenario you were asking in your last comment @mars?

**Comment by mars** [comment]
Yes, that's it @davidji99 . Let's do this!

**Pull request merged**
