### PR TITLE
Build source path may now match the current directory

### LINKED ISSUE #160: Error when Build source path matches current directory
### Terraform & Heroku Provider Version

```
Terraform v0.11.10
+ provider.heroku v1.7.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- heroku_build

### Terraform Configuration Files
```hcl
resource "heroku_app" "foobar" {
    name   = "foobar"
    region = "us"
}

resource "heroku_build" "foobar" {
  app = "${heroku_app.foobar.id}"

  source = {
    path = "./"
  }
}
```

### Debug Output

```
Error: Error running plan: 1 error(s) occurred:

* heroku_build.foobar_docker: 1 error(s) occurred:

* heroku_build.foobar_docker: Error generating build source tarball ./:
  Error generating build source tarball source-6939a70b-4a9f-f53a-95ae-08de1429ed1a.tar.gz of ./:
  archive/tar: write too long
```

### Expected Behavior

The Build is created successfully.

### Actual Behavior

The Build throws an error.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The `source.path` is the same directory containing the Terraform config.

### PR DESCRIPTION
**Pull request by mars**
Fixes #160

### CODE REVIEW

**Comment by davidji99** [comment]
👀

**Comment by talbright** [comment]
I'm buried for the next couple of weeks with some features I'm working on for an impending internal GA release...

**Comment by mars** [comment]
Good luck @talbright 🍀 😃

**Comment by mars** [comment]
Closing in favor of #181

**Pull request closed without merging**
