### PR TITLE
Fix: Upgrade to v2 requires recreation of add-ons

### LINKED ISSUE #214: Upgrade to v2 requires recreation of add-ons
### Terraform Version
```
Terraform v0.11.7
```

### Heroku Provider Version
Issue applies to the following upgrade paths
`provider.heroku v1.9.0` -> `provider.heroku v2.0.0`
`provider.heroku v1.9.0` -> `provider.heroku v2.0.1`

### Affected Resource(s)
- heroku_addon

### Terraform Configuration Files
```hcl
resource "heroku_addon" "redis" {
  app  = "foo"
  plan = "heroku-redis:private-7"

  config = {
    maxmemory_policy = "volatile-ttl"
  }
}
```
### Plan Output
```
-/+ heroku_addon.redis (new resource required)
      id:                                                         "6715ad3e-2efd-4f19-a3fc-9b0aeaabc123" => <computed> (forces new resource)
      app:                                                        "foo" => "foo"
      config.%:                                                   "2" => "1" (forces new resource)
      config.0.%:                                                 "1" => "" (forces new resource)
      config.0.maxmemory_policy:                                  "volatile-ttl" => "" (forces new resource)
      config.maxmemory_policy:                                    "" => "volatile-ttl" (forces new resource)
      config_vars.#:                                              "4" => <computed>
      name:                                                       "redis-sinuous-12312" => <computed>
      plan:                                                       "heroku-redis:private-7" => "heroku-redis:private-7"
      provider_id:                                                "resource12312312@heroku.com" => <computed>
```

### Debug Output
Available upon request. 

### Expected Behavior
Nothing changes. 

### Actual Behavior
The resource is replaced.

### Steps to Reproduce
1. Specify provider v1.9.0
2. `terraform apply`
3. Specify provider v2.0.0 or v2.0.1
4. `terraform apply`

### Important Factoids
I tried to rm and import the state but it still wants to recreate the resource with the following output:
```
-/+ heroku_addon.redis (new resource required)
      id:                                                         "6715ad3e-2efd-4f19-a3fc-9b0aeaabc123" => <computed> (forces new resource)
      app:                                                        "foo" => "foo"
      config.%:                                                   "" => "1" (forces new resource)
      config.maxmemory_policy:                                    "" => "volatile-ttl" (forces new resource)
      config_vars.#:                                              "4" => <computed>
      name:                                                       "redis-sinuous-12312" => <computed>
      plan:                                                       "heroku-redis:private-7" => "heroku-redis:private-7"
      provider_id:                                                "resource12312312@heroku.com" => <computed>
```

### References
- I believe this is related to #102

### PR DESCRIPTION
**Pull request by davidji99**
Resolves #214

### CODE REVIEW

**Comment by davidji99** [comment]
After spending a bit of time,  I've come to realize a few things about the `heroku_addon` resource:
- The platform APIs do not return any information about `config` set at addon creation. This means if a user imports `heroku_addon.redis` and has in their terrraform configuration `config = {maxmemory_policy = "volatile-ttl"}`, the next `plan` will detect a destroy and recreate since the statefile right after the import will not have `config` in it.
- The above is the current behavior because in `resourceHerokuAddonRead` doesn't set `config` attribute since it's not available remotely during an `import`.
- I can understand why `ForceNew` is set for the `heroku_addon` attribute but this setting is making things wonky. For example, could an addon's custom config be updated versus needing to destroy/recreate to apply the config change?

The quick solution is to remove the `ForceNew` so people can do some 'state surgery' themselves without the provider trying to destroy/recreate the addon. The ideal solution is for the provider to migrate the `config` attribute to the new attribute data type but this is proving a bit difficult as I cannot remotely `GET` all addon config key/value pairs. I would have to resort to somehow extracting the key from `"config.0.maxmemory_policy"`.

**Comment by davidji99** [comment]
The result of the migration takes:
```
                        "attributes": {
                            "app": "<SOME_APP>",
                            "config.#": "1",
                            "config.0.%": "1",
                            "config.0.maxmemory_policy": "volatile-ttl",
                            "config_vars.#": "1",
                            "config_vars.0": "REDIS_URL",
                            "id": "<SOME_ID>",
                            "name": "<SOME_NAME>",
                            "plan": "<SOME_PLAN>",
                            "provider_id": "<SOME_PROVIDER_ID>"
                        },
```
 "attributes": {
            "app": "<SOME_APP>",
            "config": {
              "maxmemory_policy": "volatile-ttl"
            },
            "config_vars": [
              "REDIS_URL"
            ],
            "id": "<SOME_ID>",
            "name": "<SOME_NAME>",
            "plan": "<SOME_PLAN>",
            "provider_id": "<SOME_PROVIDER_ID>"
          },
```

```

**Comment by davidji99** [comment]
What do you think @mars and @bernerdschaefer ?

**Comment by mars** [comment]
Fetching add-on config is currently not possible, as we found in #176.

**Comment by davidji99** [comment]
> #176

Oh I'm not fetching custom addon configs @mars. I'm 'migrating' the old `TypeList` of `TypeSet` config attribute to `TypeSet`. To do this, I'm parsing the statefile to get the custom addon configs. See #214.

**Comment by mars** [comment]
Ah ha, makes good sense @davidji99 😄

LGTM 👍

**Pull request merged**
