### PR TITLE
Update heroku go to v5

### PR DESCRIPTION
**Pull request by davidji99**
Basically a clone of #196.

### CODE REVIEW

**Comment by davidji99** [comment]
Hi @mars,

Please review. I have a dependency on the provider using `heroku-go v5` so I cherry-picked your 6c6cb76d904b70da26259ad9597ca7196a4a2a30 and ran `go mod tidy` and `go mod vendor` again.

Let me know what you think!

- David

**Comment by mars** [comment]
Looks good @davidji99 😄 Thanks for taking care of this!

I just started a Hashicorp CI run ⏳Will report back.

**Comment by mars** [comment]
Hashicorp CI ran out of Private Spaces, so I’ll have to clean-up the cruft & re-run later this morning.

**Comment by mars** [comment]
The CI run failed 1 test 🙅‍♂️

```
------- Stdout: -------
=== RUN   TestAccDatasourceHerokuApp_Basic
--- FAIL: TestAccDatasourceHerokuApp_Basic (10.54s)
    testing.go:538: Step 1 error: Check failed: Check 7/9 error: data.heroku_app.foobar: Attribute 'buildpacks.0' expected "https://github.com/heroku/heroku-buildpack-multi-procfile", got "heroku/go"
FAIL
```

**Comment by davidji99** [comment]
> The CI run failed 1 test 🙅‍♂️
> 
> ```
> ------- Stdout: -------
> === RUN   TestAccDatasourceHerokuApp_Basic
> --- FAIL: TestAccDatasourceHerokuApp_Basic (10.54s)
>     testing.go:538: Step 1 error: Check failed: Check 7/9 error: data.heroku_app.foobar: Attribute 'buildpacks.0' expected "https://github.com/heroku/heroku-buildpack-multi-procfile", got "heroku/go"
> FAIL
> ```

Thanks will take a look.

**Comment by davidji99** [comment]
I think I narrowed it down to the `heroku-go` client not updating the app with a new buildpack.

**Comment by davidji99** [comment]
@mars Will you run the full suite again? I updated this branch to use `heroku-go` v5.1.0.

**Comment by mars** [comment]
Running the suite now 🏃‍♂️

**Comment by davidji99** [comment]
Thanks!

**Comment by mars** [comment]
After some normal flakiness, the Hashicorp CI passed for this PR ✅

**Pull request merged**
