### PR TITLE
Handle updating an app's stack

### PR DESCRIPTION
**Pull request by dmathieu**
Changing an app stack doesn't require a fully new resource, though it will require a new build.

This also changes the retrieved stack data from `stack.name` to `build_stack.name. The stack attribute represents the stack from the latest build, whereas build_stack represents the stack that will be used on the app from now on.

### CODE REVIEW

**Comment by dmathieu** [comment]
The test failing is due to a schema issue.
I'm updating it and will be upgrading the library in the appropriate repositories.

**Comment by catsby** [comment]
Hey @dmathieu 👋 

Do you think you'll get to this, or should we close?

**Comment by dmathieu** [comment]
I'll get to this very soon.
We've been having a couple issues with unrelated schema issues, but it should be fixed very soon.

**Comment by dmathieu** [comment]
This is now working properly, and is ready for review.

```
HEROKU_API_KEY=`heroku auth:token` HEROKU_EMAIL=xxx make testacc                                           ==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -timeout 120m
?       github.com/terraform-providers/terraform-provider-heroku        [no test files]
=== RUN   TestAccHerokuAddon_importBasic
--- PASS: TestAccHerokuAddon_importBasic (9.73s)
=== RUN   TestAccHerokuApp_importBasic
--- PASS: TestAccHerokuApp_importBasic (6.81s)
=== RUN   TestAccHerokuApp_importOrganization
--- SKIP: TestAccHerokuApp_importOrganization (0.00s)
        import_heroku_app_test.go:42: HEROKU_ORGANIZATION is not set; skipping test.
=== RUN   TestAccHerokuPipelineCoupling_importBasic
--- PASS: TestAccHerokuPipelineCoupling_importBasic (7.37s)
=== RUN   TestAccHerokuPipeline_importBasic
--- PASS: TestAccHerokuPipeline_importBasic (2.45s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccHerokuAddon_Basic
--- PASS: TestAccHerokuAddon_Basic (5.41s)
=== RUN   TestAccHerokuAddon_noPlan
--- PASS: TestAccHerokuAddon_noPlan (7.94s)
=== RUN   TestAccHerokuAppFeature
--- PASS: TestAccHerokuAppFeature (7.67s)
=== RUN   TestAccHerokuApp_Basic
--- PASS: TestAccHerokuApp_Basic (4.28s)
=== RUN   TestAccHerokuApp_Change
--- PASS: TestAccHerokuApp_Change (7.22s)
=== RUN   TestAccHerokuApp_NukeVars
--- PASS: TestAccHerokuApp_NukeVars (7.38s)
=== RUN   TestAccHerokuApp_Buildpacks
--- PASS: TestAccHerokuApp_Buildpacks (10.13s)
=== RUN   TestAccHerokuApp_ExternallySetBuildpacks
--- PASS: TestAccHerokuApp_ExternallySetBuildpacks (5.76s)
=== RUN   TestAccHerokuApp_Organization
--- SKIP: TestAccHerokuApp_Organization (0.00s)
        resource_heroku_app_test.go:198: HEROKU_ORGANIZATION is not set; skipping test.
=== RUN   TestAccHerokuApp_Space
--- SKIP: TestAccHerokuApp_Space (0.00s)
        resource_heroku_app_test.go:225: HEROKU_ORGANIZATION is not set; skipping test.
=== RUN   TestAccHerokuApp_EmptyConfigVars
--- PASS: TestAccHerokuApp_EmptyConfigVars (3.44s)
=== RUN   TestAccHerokuCert_EU
--- PASS: TestAccHerokuCert_EU (39.58s)
=== RUN   TestAccHerokuCert_US
--- PASS: TestAccHerokuCert_US (28.41s)
=== RUN   TestAccHerokuDomain_Basic
--- PASS: TestAccHerokuDomain_Basic (4.34s)
=== RUN   TestAccHerokuDrain_Basic
--- PASS: TestAccHerokuDrain_Basic (4.85s)
=== RUN   TestAccHerokuPipelineCoupling_Basic
--- PASS: TestAccHerokuPipelineCoupling_Basic (6.86s)
=== RUN   TestAccHerokuPipeline_Basic
--- PASS: TestAccHerokuPipeline_Basic (3.17s)
=== RUN   TestAccHerokuSpace_Basic
--- SKIP: TestAccHerokuSpace_Basic (0.00s)
        resource_heroku_space_test.go:35: HEROKU_ORGANIZATION is not set; skipping test.
=== RUN   TestPipelineStage
--- PASS: TestPipelineStage (0.00s)
=== RUN   TestValidateUUID
--- PASS: TestValidateUUID (0.00s)
PASS
ok      github.com/terraform-providers/terraform-provider-heroku/heroku 172.864s
```

**Pull request merged**
